// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OwnerDataExt;

namespace Persistence.DataBase.Migrations
{
    [DbContext(typeof(OwneDbContext))]
    [Migration("20211210135732_RealEstateMigra")]
    partial class RealEstateMigra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.PaymentMethodModel", b =>
                {
                    b.Property<long>("PaymentMethodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentMethodID");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateAnualBenefitModel", b =>
                {
                    b.Property<long>("RealEstateAnualBenefitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AnnualBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EfectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("RealEstatePaymentFrecuencyID")
                        .HasColumnType("bigint");

                    b.Property<long>("RealEstateRegistryID")
                        .HasColumnType("bigint");

                    b.HasKey("RealEstateAnualBenefitID");

                    b.HasIndex("RealEstatePaymentFrecuencyID");

                    b.HasIndex("RealEstateRegistryID");

                    b.ToTable("RealEstateAnualBenefit");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateBanksTransferenceModel", b =>
                {
                    b.Property<long>("RealEstateBanksTransferenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("BeneficiaryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntermediaryBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RealEstateRegistryID")
                        .HasColumnType("bigint");

                    b.Property<int>("RealEstatedBankID")
                        .HasColumnType("int");

                    b.Property<long>("RealStateRegistryID")
                        .HasColumnType("bigint");

                    b.HasKey("RealEstateBanksTransferenceID");

                    b.HasIndex("RealEstateRegistryID");

                    b.HasIndex("RealEstatedBankID");

                    b.ToTable("RealEstateBanksTransference");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateContactInfoModel", b =>
                {
                    b.Property<long>("RealEstateContactInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Extension")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RealEstatePhoneTypeID")
                        .HasColumnType("int");

                    b.Property<long>("RealEstateRegistryID")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RealEstateContactInfoID");

                    b.HasIndex("RealEstatePhoneTypeID");

                    b.HasIndex("RealEstateRegistryID");

                    b.ToTable("RealEstateContactInfo");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateDocumentSource", b =>
                {
                    b.Property<int>("RealEstateDocumentSourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealEstateDocumentSourceID");

                    b.ToTable("RealEstateDocumentSource");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateLocationModel", b =>
                {
                    b.Property<int>("RealEstateLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealEstateLocationID");

                    b.ToTable("RealEstateLocation");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstatePaymentFrecuencyModel", b =>
                {
                    b.Property<long>("RealEstatePaymentFrecuencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("FrecuenceValue")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealEstatePaymentFrecuencyID");

                    b.ToTable("RealEstatePaymentFrecuency");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstatePaymentHistoryModel", b =>
                {
                    b.Property<long>("RealEstatePaymentHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EfectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("RealEstateRegistryID")
                        .HasColumnType("bigint");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<long>("processCode")
                        .HasColumnType("bigint");

                    b.HasKey("RealEstatePaymentHistory");

                    b.HasIndex("RealEstateRegistryID");

                    b.ToTable("RealEstatePaymentHistory");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstatePhoneTypeModel", b =>
                {
                    b.Property<int>("RealEstatePhoneTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealEstatePhoneTypeID");

                    b.ToTable("RealEstatePhoneType");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateProjectTypeModel", b =>
                {
                    b.Property<long>("RealEstateProjectTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealEstateProjectTypeID");

                    b.ToTable("RealEstateProjectType");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstatePropertyModel", b =>
                {
                    b.Property<long>("RealEstatePropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RealEstateLocationID")
                        .HasColumnType("int");

                    b.Property<int>("RealEstatePropertyTypeID")
                        .HasColumnType("int");

                    b.HasKey("RealEstatePropertyID");

                    b.HasIndex("RealEstateLocationID");

                    b.HasIndex("RealEstatePropertyTypeID");

                    b.ToTable("RealEstateProperty");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstatePropertyOBenefitModel", b =>
                {
                    b.Property<long>("RealEstateAnualBenefitID")
                        .HasColumnType("bigint");

                    b.Property<long>("RealEstatePropertyID")
                        .HasColumnType("bigint");

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RealEstateAnualBenefitID", "RealEstatePropertyID");

                    b.HasIndex("RealEstatePropertyID");

                    b.ToTable("RealEstatePropertyOBenefit");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstatePropertyTypeModel", b =>
                {
                    b.Property<int>("RealEstatePropertyTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RealEstateProjectTypeID")
                        .HasColumnType("bigint");

                    b.HasKey("RealEstatePropertyTypeID");

                    b.HasIndex("RealEstateProjectTypeID");

                    b.ToTable("RealEstatePropertyType");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateRegOwneInfoModel", b =>
                {
                    b.Property<long>("RealEstateRegOwneInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentID")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RealEstateRegistryID")
                        .HasColumnType("bigint");

                    b.HasKey("RealEstateRegOwneInfoID");

                    b.HasIndex("RealEstateRegistryID");

                    b.ToTable("RealEstateRegOwneInfo");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateRegistryModel", b =>
                {
                    b.Property<long>("RealEstateRegistryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PaymentMethodID")
                        .HasColumnType("bigint");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("RealEstateRegistryID");

                    b.HasIndex("PaymentMethodID");

                    b.ToTable("RealEstateRegistry");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateTransactionModel", b =>
                {
                    b.Property<long>("RealEstateTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RealEstateRegistryID")
                        .HasColumnType("bigint");

                    b.Property<int>("RealEstateTransactionTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("RealEstateTransactionID");

                    b.HasIndex("RealEstateRegistryID");

                    b.HasIndex("RealEstateTransactionTypeID");

                    b.ToTable("RealEstateTransaction");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateTransactionTypeModel", b =>
                {
                    b.Property<int>("RealEstateTransactionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.HasKey("RealEstateTransactionTypeID");

                    b.ToTable("RealEstateTransactionType");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstatedBankModel", b =>
                {
                    b.Property<int>("RealEstatedBankID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("BankAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CretionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoutingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealEstatedBankID");

                    b.ToTable("RealEstatedBank");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealStateDocumentsModel", b =>
                {
                    b.Property<long>("RealStateDocumentsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RealEstateDocumentSourceID")
                        .HasColumnType("int");

                    b.Property<long>("RealEstateRegistryID")
                        .HasColumnType("bigint");

                    b.Property<int>("RealStateDocumentsTypeID")
                        .HasColumnType("int");

                    b.Property<long>("ReferenceID")
                        .HasColumnType("bigint");

                    b.HasKey("RealStateDocumentsID");

                    b.HasIndex("RealEstateDocumentSourceID");

                    b.HasIndex("RealEstateRegistryID");

                    b.HasIndex("RealStateDocumentsTypeID");

                    b.ToTable("RealStateDocuments");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealStateDocumentsTypeModel", b =>
                {
                    b.Property<int>("RealStateDocumentsTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("RealStateDocumentsTypeID");

                    b.ToTable("RealStateDocumentsType");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateAnualBenefitModel", b =>
                {
                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstatePaymentFrecuencyModel", "RealEstatePaymentFrecuency")
                        .WithMany()
                        .HasForeignKey("RealEstatePaymentFrecuencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateRegistryModel", "RealEstateRegistry")
                        .WithMany()
                        .HasForeignKey("RealEstateRegistryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateBanksTransferenceModel", b =>
                {
                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateRegistryModel", "RealEstateRegistry")
                        .WithMany("RealEstateBanksTransference")
                        .HasForeignKey("RealEstateRegistryID");

                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstatedBankModel", "RealEstatedBank")
                        .WithMany()
                        .HasForeignKey("RealEstatedBankID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateContactInfoModel", b =>
                {
                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstatePhoneTypeModel", "RealEstatePhoneType")
                        .WithMany("RealEstateContactInfo")
                        .HasForeignKey("RealEstatePhoneTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateRegistryModel", "RealEstateRegistry")
                        .WithMany("RealEstateContactInfo")
                        .HasForeignKey("RealEstateRegistryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstatePaymentHistoryModel", b =>
                {
                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateRegistryModel", "RealEstateRegistry")
                        .WithMany("RealEstatePaymentHistory")
                        .HasForeignKey("RealEstateRegistryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstatePropertyModel", b =>
                {
                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateLocationModel", "RealEstateLocation")
                        .WithMany("RealEstateProperty")
                        .HasForeignKey("RealEstateLocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstatePropertyTypeModel", "RealEstatePropertyType")
                        .WithMany("RealEstateProperty")
                        .HasForeignKey("RealEstatePropertyTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstatePropertyOBenefitModel", b =>
                {
                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateAnualBenefitModel", "RealEstateAnualBenefit")
                        .WithMany("RealEstatePropertyOBenefit")
                        .HasForeignKey("RealEstateAnualBenefitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstatePropertyModel", "RealEstateProperty")
                        .WithMany("RealEstatePropertyOBenefit")
                        .HasForeignKey("RealEstatePropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstatePropertyTypeModel", b =>
                {
                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateProjectTypeModel", "RealEstateProjectType")
                        .WithMany("RealEstatePropertyType")
                        .HasForeignKey("RealEstateProjectTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateRegOwneInfoModel", b =>
                {
                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateRegistryModel", "RealEstateRegistry")
                        .WithMany("RealEstateRegOwneInfo")
                        .HasForeignKey("RealEstateRegistryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateRegistryModel", b =>
                {
                    b.HasOne("Persistence.DataBase.RealEstateMoldels.PaymentMethodModel", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodID");
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealEstateTransactionModel", b =>
                {
                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateRegistryModel", "RealEstateRegistry")
                        .WithMany("RealEstateTransaction")
                        .HasForeignKey("RealEstateRegistryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateTransactionTypeModel", "RealEstateTransactionType")
                        .WithMany()
                        .HasForeignKey("RealEstateTransactionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.DataBase.RealEstateMoldels.RealStateDocumentsModel", b =>
                {
                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateDocumentSource", "RealEstateDocumentSource")
                        .WithMany("RealStateDocuments")
                        .HasForeignKey("RealEstateDocumentSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealEstateRegistryModel", "RealEstateRegistry")
                        .WithMany("RealStateDocuments")
                        .HasForeignKey("RealEstateRegistryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.DataBase.RealEstateMoldels.RealStateDocumentsTypeModel", "RealStateDocumentsType")
                        .WithMany("RealStateDocuments")
                        .HasForeignKey("RealStateDocumentsTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
